import {
  ClerkProvider,
  SignIn,
  SignedIn,
  SignedOut
} from '@clerk/nextjs';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
import Header from '@/components/Header';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Email Verifier",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedOut>
            <div className='flex items-center flex-col justify-center h-screen'>
              <div className='flex items-center flex-col gap-y-10 mb-10'>
                <Image src="/assets/logo.png" width={44} height={40} alt='logo' />
                <h1 className='text-[24px] font-semibold'>Welcome back</h1>
              </div>
              <SignIn routing='hash' />
            </div>
          </SignedOut>
          <SignedIn>
            <Header />
            {children}
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
